cpp_builder: fix MSBuild false positive build errors
Before this commit, the parse_failed_build() function was reporting the
`zlib_with_header_78.cpp` source file as having caused a build error,
when in fact it did not. This was also demonstrated by the `msbuild_1`
test in `builder/spec/cpp/cpp_builder_spec.rb` before this commit - the
test failure message looked like this:

```console
$ rspec builder/spec/cpp/cpp_builder_spec.rb
...

Failures:

  1) CppBuilder msbuild_1 #parse_failed_build parses failed build information for msbuild
     Failure/Error:
       expect(@builder.parse_failed_build('test_out/cpp_stl_98/build-1.log').uniq).to eq [
         [:bare, 'enum_to_i_class_border_2.cpp'],
         'c:/projects/ci-targets/tests/compiled/cpp_stl_98/enum_to_i_class_border_2.cpp',
         'c:/projects/ci-targets/tests/compiled/cpp_stl_98/io_local_var.cpp',
       ]

       ...

       Diff:
       @@ -1,4 +1,5 @@
        [[:bare, "enum_to_i_class_border_2.cpp"],
         "c:/projects/ci-targets/tests/compiled/cpp_stl_98/enum_to_i_class_border_2.cpp",
       - "c:/projects/ci-targets/tests/compiled/cpp_stl_98/io_local_var.cpp"]
       + "c:/projects/ci-targets/tests/compiled/cpp_stl_98/io_local_var.cpp",
       + [:bare, "zlib_with_header_78.cpp"]]
```

As you can see in
`builder/spec/cpp/msbuild_1/test_out/cpp_stl_98/build-1.log`, the
problem is that the `zlib_with_header_78.cpp` file name read from the
first line of the following snippet is saved to the `orig_cpp_filename`
variable (as it should), but it remained there until the last line of
the following snippet (`  c:\...\enum_to_i_class_border_2.h(18): error
C2061: ...`), so the file `enum_to_i_class_border_2.h` containing the
error was assumed to be included from `zlib_with_header_78.cpp`, which
was therefore excluded from the build:

```
  zlib_with_header_78.cpp
  Generating Code...
Done Building Project "C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj.metaproj" (default targets) -- FAILED.
Done Building Project "C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\KS_TEST_CPP_STL.sln" (default targets) -- FAILED.
Build FAILED.
"C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\KS_TEST_CPP_STL.sln" (default target) (1) ->
"C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj.metaproj" (default target) (3) ->
"C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\projects\ci-targets\runtime\cpp_stl\kaitai\kaitaistream.cpp(492): warning C4267: '=': conversion from 'size_t' to 'uInt', possible loss of data [C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj]
  ...
  C:\projects\ci-targets\tests\compiled\cpp_stl_98\yaml_ints.cpp(51): warning C4309: '=': truncation of constant value [C:\...\ks_tests.vcxproj]
"C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\KS_TEST_CPP_STL.sln" (default target) (1) ->
"C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj.metaproj" (default target) (3) ->
"C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj" (default target) (4) ->
(ClCompile target) ->
  c:\projects\ci-targets\tests\compiled\cpp_stl_98\enum_to_i_class_border_2.h(18): error C2061: syntax error: identifier 'enum_to_i_class_border_1_t' [C:\...\ks_tests.vcxproj]
```

So this bug was a combination of 2 things:

1. The parse_failed_build() function treated errors from the summary at
   the end of MSBuild output (after the `(ClCompile target) ->` line) as
   "new" errors (even though it only ever lists all warnings/errors that
   were reported before). We don't want that not only because it's
   redundant to process errors that were already processed, but also
   because this summary only lists the one-line "titles" of all errors,
   not the details. Which was also the problem here: our code expected
   .h errors to be preceded by a line like `  zlib_with_header_78.cpp`
   (which indicates the .cpp file that included the .h file containing
   the error), but this was not the case.

2. The `orig_cpp_filename` was `nil` at the beginning, but once set, it
   was never cleared again until the end of the log, so it lived much
   longer than expected. To avoid `orig_cpp_filename` being incorrectly
   assigned to an unrelated .h file later in the log, we now clear
   `orig_cpp_filename` as soon as possible, i.e. on the first line that
   doesn't report an `error` or a `warning`. This may eventually turn
   out to be too strict, because the warning/error message can sometimes
   continue on subsequent lines like this:

   ```
   |  test_bits_simple.cpp
   |C:\Tools\vcpkg\installed\x64-windows\include\boost/test/tools/old/impl.hpp(107): warning C4805: '==': unsafe mix of type 'const Left' and type 'const Right' in operation [C:\projects\ci-targets\tests\compiled\cpp_stl_98\bin\ks_tests.vcxproj]
   |          with
   |          [
   |              Left=bool
   |          ]
   |          and
   |          [
   |              Right=int
   |          ]
   ```

   ... but at least if this really becomes a problem in the future,
   we'll get a clear signal in the form of a CI failure as well as
   logging messages with line numbers so we can quickly diagnose what
   happened.

Last but not least, this commit adds logging of interesting events
related to error handling in .h files in MSBuild mode (errors in .h
files are usually not that common, so there shouldn't be many of these
log messages either).