EnumLongRangeU: test `2**64 - 1`, stop avoiding KSC compile error
This will be followed by a change to the compiler that fixes the compile
error. For reference, the compile error message with the currently
latest KSC 0.12-SNAPSHOT
https://github.com/kaitai-io/kaitai_struct_compiler/tree/4c19506ac6ccde9826da8e70636b239b871d3a14
(or KSC 0.11) is the following:

```
formats/enum_long_range_u.ksy: /enums/constants:
        error: expected int, got 18446744073709551615 (class java.math.BigInteger)
```