StrEncodingsEscaping{Enc,ToS}: fix C# .NET <6 compat
Should fix StrEncodingsEscaping{Enc,ToS} for
`csharp/{net48-windows-x64,netcore2.2.103-linux-x86_64,netcore3.0.100-linux-x86_64}`.

Currently, the only C# target where these tests compile fine (they have
a `failed` status, but that's proof they actually ran) is
`csharp/netcore6.0-linux-x86_64`. The remaining 3 previously mentioned
targets have a status of `spec_build_failed` and the error messages look
like this (see https://github.com/kaitai-io/ci_artifacts/blob/7fa0665233652887423ff3577e5b873e48f67540/test_out/csharp/build-1.log#L23-L24):

```
D:\a\ci_targets\ci_targets\tests\spec\csharp\kaitai_struct_csharp_tests\tests\SpecStrEncodingsEscapingEnc.cs(39,44):
    error CS0246: The type or namespace name 'String' could not be found (are you missing a using directive or an assembly reference?)
    [D:\a\ci_targets\ci_targets\tests\spec\csharp\kaitai_struct_csharp_tests_netframework\kaitai_struct_csharp_tests_netframework.csproj]
D:\a\ci_targets\ci_targets\tests\spec\csharp\kaitai_struct_csharp_tests\tests\SpecStrEncodingsEscapingToS.cs(39,44):
    error CS0246: The type or namespace name 'String' could not be found (are you missing a using directive or an assembly reference?)
    [D:\a\ci_targets\ci_targets\tests\spec\csharp\kaitai_struct_csharp_tests_netframework\kaitai_struct_csharp_tests_netframework.csproj]
```

Using `string` instead of `String` seems to solve this problem and
it's generally recommended anyway, see:

* https://www.reddit.com/r/csharp/comments/t3c0rd/tip_of_the_day_do_you_know_what_is_the_difference/
* https://blog.paranoidcoding.org/2019/04/08/string-vs-String-is-not-about-style.html