java_builder: avoid `NoClassDefFoundError` as test failure
Occasionally, tests that should be marked as `format_build_failed` are
still run by TestNG and fail at runtime due to an error like
`java.lang.NoClassDefFoundError:
io/kaitai/struct/testformats/ExprOpsParens`. It seems that this might be
caused by compiled .class files in the `compiled/java/bin` folder
remaining from previous attempts, so let's see if clearing the `bin`
folder before each attempt solves the problem.

We have our own machinery to detect and report tests with status
`format_build_failed`, so it will be more consistent to prevent the test
from being "run" by TestNG, avoid `java.lang.NoClassDefFoundError` from
being propagated as the test `failure` and rely on our machinery
instead.